name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # 给 mocha 添加执行权限，避免权限拒绝
      - name: Add execute permission to mocha
        run: chmod +x node_modules/.bin/mocha

      - name: Run tests
        run: npm test
